### ISSUE TITLE
https request fails with "sslv3 handshake failure"

### ISSUE THREAD

**Issue by saurabh02** [CitrineInformatics/python-citrination-client#1]
Hello,

I'm using Mac OS X and the python-citrination-client to access the API, but a search query resulted in the following error,

SSLError: ("bad handshake: Error([('SSL routines', 'SSL23_GET_SERVER_HELLO', 'sslv3 alert handshake failure')],)",)

Seems like Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries, which is resulting in these errors. I temporarily resolved this by making just http (without SSL) requests, but would there be a better solution?

Thanks
Saurabh

**Comment by jsomara** [comment]
You're exactly right, the Apple crypto libraries don't like the CloudFlare SSL cert we use on citrination.com. This issue will resolve itself when we upgrade citrination.com to use a proper EV cert, but until then I think making a regular HTTP request is the best workaround.

**Comment by saurabh02** [comment]
Okay thanks.

Saurabh
