### ISSUE TITLE
upload_file ignores root_path

### ISSUE THREAD

**Issue by Setogit** [CitrineInformatics/python-citrination-client#147]
https://github.com/CitrineInformatics/python-citrination-client/blob/5af15373247900654b05a580c0706d60d0a543fe/citrination_client/client.py#L352

**Comment by Setogit** [comment]
Apparently, major refactoring is going on in "develop" branch.  We can close this issue.

**Comment by maxhutch** [comment]
@Setogit thanks for the report!

@mcgalcode can you confirm that this is resolved in the refactor and, if so, close here?

**Comment by mcgalcode** [comment]
It will be resolved with our next release.  `upload_file` is removed and replaced with `upload` which allows you to specify a destination path. 

`upload` is also present in the current version of the client:

`client.upload(my_dataset_id, "path/to/my/file", "desired_name_of_file_in_dataset.ext")`

**Comment by mcgalcode** [comment]
cc: @maxhutch
