### ISSUE TITLE
Views metadata obtained through API creates an invalid JSON

### ISSUE THREAD

**Issue by enze-chen** [CitrineInformatics/python-citrination-client#221]
After I create a view, and call `client.data_views.get(ID)`, the JSON that it returns for the metadata appears to be invalid. I cannot figure out why (it seems like all brackets match). Not urgent; also not sure if this is a big issue, since even as invalid I can still access the fields with list/dict syntax.

Reproducible code:
```python
client = CitrinationClient(os.environ['CITRINATION_API_KEY'], 'https://citrination.com')
dv_id = '7565'
view_metadata = client.data_views.get(dv_id)
print('The metadata for this view contains:\n{}'.format(view_metadata))
```

**Comment by EricLundberg** [comment]
Got it, thanks! I'm adding that to CT-203, you can track its progress there: https://citrine.atlassian.net/browse/CT-203

**Comment by sparadiso** [comment]
Could you share that view with me @enze-chen ?

**Comment by enze-chen** [comment]
...I just went through the same steps, and generated a valid metadata. Single quotes became double quotes, and None became null, among other small changes. I think we're OK now, not sure what happened. This can be closed.
