### ISSUE TITLE
Pagination doesn't seem to be working

### ISSUE THREAD

**Issue by maxhutch** [CitrineInformatics/python-citrination-client#39]
I have a query that contains 896 results, so it requires pagination:
```
pos = 0
total = 1
time = 0.0
hits = []
while pos < total:
    sub_query = deepcopy(query)
    sub_query.from_record = pos
    sub_query.per_page = 50
    pifSearchResult = client.search(sub_query)
    total = pifSearchResult.total_num_hits
    pos += len(pifSearchResult.hits)
    time += pifSearchResult.took
    hits.extend(pifSearchResult.hits)
    sleep(10)


print("Query took {} ms to complete".format(time))
print("Query returned {} results".format(total))
print(len(hits))
```

I would expect `len(hits) == pifSearchResult.total_num_hits`, but, instead, I get:
```
Query took 87659.0 ms to complete
Query returned 896 results
900
```
Inspecting the hit results shows that the same block of results is repeated.

**Comment by kjaym** [comment]
I think that your pagination variable names are not correct. They should be `from_index` and `size`, not `from_record` and `per_page`. Do we have the latter documented somewhere?
