### ISSUE TITLE
Utility to paginate through results for users

### ISSUE THREAD

**Issue by sparadiso** [CitrineInformatics/python-citrination-client#75]
We should provide users with a utility that paginates for them - pagination is an engineering construct, not a meaningful materials science concept. As a materials scientist, it surprises me that I can't ask for information and retrieve the list of results immediately. I'd rather provide a PifQuery and a total record count and get back a list of hits equal to (or less than) the requested record count.

**Comment by kjaym** [comment]
If you don't ask for a max number of records or set a starting index then it will iterate for you.

**Comment by sparadiso** [comment]
```
resp = client.search(PifQuery(include_datasets=[150146], size=1500, random_results=True, return_system=True))

lst = list()
for hit in resp.hits:
    lst.append(hit.system.uid)
    print len(lst)
```

That code prints up to 500.

**Comment by sparadiso** [comment]
Put another way, I think that's an example of an intuitive request with an unintuitive response (although I understand why it behaves this way).

**Comment by kjaym** [comment]
Sure, but if you don't put a size, then it does behave the way that you are suggesting. You could update https://github.com/CitrineInformatics/python-citrination-client/blob/develop/citrination_client/client.py#L47-L66 If you want to only check for None-valued from_index.

**Comment by sparadiso** [comment]
That still leaves my request unsupported. IMO the following code should work as expected:

```
resp = client.search(PifQuery(include_datasets=[150146], size=1500, return_system=True))

lst = list()
for hit in resp.hits:
    lst.append(hit.system.uid)
print len(lst)

>> 1500
```

**Comment by sparadiso** [comment]
n=1 :p

**Comment by sparadiso** [comment]
(note the motivation here is that we're starting to actually get large datasets on the site, so getting a representative subsample is more likely to be a common request)

**Comment by kjaym** [comment]
If you look at line 47 of the above, remove `pif_query.size is None`, then slightly adjust the logic on line 49 to take into account the requested size, then you'll get exactly that behavior.

**Comment by maxhutch** [comment]
@sparadiso I can handle this if you're not working on it.  Just assign it to me.

**Comment by sparadiso** [comment]
_we have the technology_

**Comment by sparadiso** [comment]
I will not have time to do it until EOD at earliest (I'm done w/ pcc too, though). Feel free!

**Comment by jling11** [comment]
This whole chain makes me both laugh and cry.  I want this fix to happen.

**Comment by jling11** [comment]
Is there a jira card for this?

**Comment by sparadiso** [comment]
I don't think so.
